php74.spec
Bump to latest upstream 7.4.7
Small fix to changelog date to avoid warning from rpmbuild
=> Bump to latest upstream 7.4.7

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.9
=> Update to upstream 7.4.9

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.10
=> Upstream 7.4.10

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.11
=> Upstream 7.4.11

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.12
=> Upstream 7.4.12

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.13
=> Upstream 7.4.13

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.14
=> Upstream 7.4.14

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.15
=> Upstream 7.4.15

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.16
=> Upstream 7.4.16

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.18
=> Upstream 7.4.18

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.19
This is a small followup release to fix a pgsql bug that was introduced in 7.4.18.
=> Upstream 7.4.19

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.20
=> Uptream 7.4.20

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.21
=> Upstream 7.4.21

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.22
=> Upstream 7.4.22

php74.spec
Updated spec file with latest https://www.php.net/ChangeLog-7.php#7.4.23
=> Upstream 7.4.23

php74.spec
Latest from upstream. This is a security update.
https://www.php.net/ChangeLog-7.php#7.4.24
=> Latest update from upstream: PHP 7.4.24

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.26
=> Upstream 7.4.26

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.27
Missed this last month...
=> Upstream 7.4.27

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.28
Fixes #33
=> Upstream 7.4.28

php74.spec
https://www.php.net/ChangeLog-7.php#7.4.29
=> Upstream 7.4.29

php74.spec
Latest from upstream. This is a security update.
https://www.php.net/ChangeLog-7.php#7.4.30
Closes #37.
=> Upstream 7.4.30
